/**
 * MCP tool definitions.
 * Prompts removed in v0.13.0 — tool descriptions guide LLM behavior directly.
 */

export const TOOLS = [
  { name: 'search_signals', description: 'Search signals by keyword and optional filters. Returns lean results (no description) with truncation metadata. Use get_signal for full detail.', inputSchema: { type: 'object', properties: { query: { type: 'string' }, type: { type: 'string', enum: ['mention', 'friction', 'problem', 'deal-loss'] }, severity: { type: 'string', enum: ['Low', 'Medium', 'High'] }, unlinked_only: { type: 'boolean' } }, required: ['query'] } },
  { name: 'get_signal', description: 'Fetch full detail for a single signal by ID, including description and raw_payload. Use after search_signals to drill into a specific signal.', inputSchema: { type: 'object', properties: { signal_id: { type: 'string' } }, required: ['signal_id'] } },
  { name: 'search_customers', description: 'Look up customer accounts by name. Always call before create_signal.', inputSchema: { type: 'object', properties: { query: { type: 'string' } }, required: ['query'] } },
  { name: 'search_initiatives', description: 'Search roadmap initiatives by keyword. Returns impact scores.', inputSchema: { type: 'object', properties: { query: { type: 'string' } }, required: ['query'] } },
  { name: 'rank_initiatives', description: 'Rank all initiatives by impact score (Fermi Leverage Model). Returns initiatives sorted by score with full impact breakdown, plus count of unlinked signals in the triage queue. Use this to answer "what should we build next?"', inputSchema: { type: 'object', properties: {}, required: [] } },
  { name: 'create_initiative', description: 'Create a new roadmap initiative. Use search_initiatives first to avoid duplicates. Optionally supply signal_ids to link them atomically on creation.', inputSchema: { type: 'object', properties: { title: { type: 'string', maxLength: 120 }, brief: { type: 'string' }, signal_ids: { type: 'array', items: { type: 'string' } } }, required: ['title'] } },
  { name: 'create_signal', description: 'Ingest a single customer feedback signal. For multiple signals, prefer batch_create_signals.', inputSchema: { type: 'object', properties: { summary: { type: 'string', maxLength: 200 }, description: { type: 'string' }, type: { type: 'string', enum: ['mention', 'friction', 'problem', 'deal-loss'] }, category: { type: 'string', enum: ['feature', 'workflow'] }, severity: { type: 'string', enum: ['Low', 'Medium', 'High'] }, source: { type: 'string', enum: ['Slack', 'Intercom', 'E-Mail', 'Support ticket', 'Sales call', 'User interview'] }, account_id: { type: 'string' } }, required: ['summary', 'type', 'category', 'severity'] } },
  { name: 'batch_create_signals', description: 'Ingest multiple feedback signals in one call. Accepts up to 100 signals as an array — USE THIS instead of calling create_signal in a loop. All tagged ingestion_source: mcp.', inputSchema: { type: 'object', properties: { signals: { type: 'array', maxItems: 100, items: { type: 'object', properties: { summary: { type: 'string', maxLength: 200 }, description: { type: 'string' }, type: { type: 'string', enum: ['mention', 'friction', 'problem', 'deal-loss'] }, category: { type: 'string', enum: ['feature', 'workflow'] }, severity: { type: 'string', enum: ['Low', 'Medium', 'High'] }, source: { type: 'string', enum: ['Slack', 'Intercom', 'E-Mail', 'Support ticket', 'Sales call', 'User interview'] }, account_id: { type: 'string' } }, required: ['summary', 'type', 'category', 'severity'] } } }, required: ['signals'] } },
  { name: 'create_customer', description: 'Add a new customer. RESTRICTED to Owners. Always search_customers first.', inputSchema: { type: 'object', properties: { name: { type: 'string' }, website: { type: 'string' }, tier: { type: 'string', enum: ['Startup', 'Standard', 'Enterprise'] }, arr: { type: 'number' } }, required: ['name'] } },
  { name: 'link_to_initiative', description: 'Connect signals to a roadmap initiative with reasoning.', inputSchema: { type: 'object', properties: { signal_ids: { type: 'array', items: { type: 'string' } }, initiative_id: { type: 'string' }, reasoning: { type: 'string' } }, required: ['signal_ids', 'initiative_id', 'reasoning'] } },
  { name: 'enrich_initiative', description: 'Strengthen an initiative with hypothesis, metrics, and linked signals. Also supports renaming the initiative title.', inputSchema: { type: 'object', properties: { initiative_id: { type: 'string' }, title: { type: 'string', maxLength: 120 }, refined_hypothesis: { type: 'string' }, target_outcome: { type: 'object', properties: { target_description: { type: 'string' }, metric: { type: 'string' }, validation_window_days: { type: 'number' } } }, health_metrics: { type: 'object', description: 'Key-value pairs where each value MUST be numeric.' }, additional_signal_ids: { type: 'array', items: { type: 'string' } }, start_date: { type: 'string' }, target_date: { type: 'string' } }, required: ['initiative_id'] } },
  { name: 'update_signal', description: 'Update one or more fields on an existing signal. Use to correct ingestion errors (wrong account_id, severity, type) without deleting and recreating. Supply only the fields to change.', inputSchema: { type: 'object', properties: { signal_id: { type: 'string' }, account_id: { type: 'string' }, severity: { type: 'string', enum: ['Low', 'Medium', 'High'] }, type: { type: 'string', enum: ['mention', 'friction', 'problem', 'deal-loss'] }, summary: { type: 'string', maxLength: 200 }, description: { type: 'string' }, source: { type: 'string', enum: ['Slack', 'Intercom', 'E-Mail', 'Support ticket', 'Sales call', 'User interview'] } }, required: ['signal_id'] } },
];
